### ISSUE TITLE
Make arcyon Windows compatible

### ISSUE THREAD

**Issue by jgr3go** [bloomberg/phabricator-tools#15]
When trying to run arcyon on a Windows environment, you get the error:
```python
$ arcyon
Traceback (most recent call last):
  File "c:/Program Files/arcanist/phabricator-tools/bin/arcyon", line 31, in <module>
    import aoncmd_arcyon  # noqa
  File "c:\Program Files\arcanist\phabricator-tools\py\aon\aoncmd_arcyon.py", line 33, in <module>
    import aoncmd_gitdiffhelper
  File "c:\Program Files\arcanist\phabricator-tools\py\aon\aoncmd_gitdiffhelper.py", line 31, in <module>
    import abdt_branch
  File "c:\Program Files\arcanist\phabricator-tools\py\abd\abdt_branch.py", line 61, in <module>
    import abdt_differ
  File "c:\Program Files\arcanist\phabricator-tools\py\abd\abdt_differ.py", line 32, in <module>
    import phlgit_diff
  File "c:\Program Files\arcanist\phabricator-tools\py\phl\phlgit_diff.py", line 26, in <module>
    import phlsys_fs
  File "c:\Program Files\arcanist\phabricator-tools\py\phl\phlsys_fs.py", line 33, in <module>
    import fcntl
ImportError: No module named fcntl
```

It seems that fcntl is used to get file lock permissions, but no fcntl module exists for Windows.  It's worth noting that arcanist uses the EDITOR config variable to get blocking sessions ([PhutilInteractiveEditor.php](https://github.com/phacility/libphutil/blob/13899e4637d376f29994604c6ee19750b9985fbf/src/console/PhutilInteractiveEditor.php)) so it is possible, just not with the fcntl module. 

Worth noting, I have no idea if this is the only code that's not Windows compatible, so this request may be more than just what I've listed here.

**Comment by jgr3go** [comment]
Worth it to note, I have no idea if this is the only thing that's not windows compatible, but it's the first error I've found

**Comment by flippingtables** [comment]
I found a fix for this. Create a file called 'fcntl.py' and put it in the py/phl/ directory.
Paste this code in the file:
```
def fcntl(fd, op, arg=0):
    return 0

def ioctl(fd, op, arg=0, mutable_flag=True):
    if mutable_flag:
        return 0
    else:
        return ""

def flock(fd, op):
    return

def lockf(fd, operation, length=0, start=0, whence=0):
    return
```

**Comment by aevri** [comment]
Maybe we should split out the platform-dependent bits of `phlsys_fs` into their own module, perhaps called `phlsys_fsunix` or similar. That way we would still get errors if we try to use unimplemented functionality, arcyon probably doesn't need to use `phlsys_fsunix` and would then work on Windows.
